### ISSUE TITLE
Some suggestions about this software

### ISSUE THREAD

**Issue by infulenceyang** [cabinz/vocab-manager#3]
First of all, I think this work is interesting, thank you for your efforts.

But I have some suggestions for your work:
1>. The tag can't be deleted if one word has been tagged.
2>. If I set too many tags, such as 30 items, I can't find all the tags in the Word Viwer interface.
Maybe the second suggestion is a bug?
![image](https://user-images.githubusercontent.com/98532251/224651364-522f02a5-5d89-4492-976e-acccd8fd90b8.png)

**Comment by cabinz** [comment]
Thank you for using and providing feedback on this software! 

This tool was initially developed based on my personal needs, and it has fulfilled its purpose. Due to my busy work schedules, it may not be possible to address any bugs or implement new features in the short term.

My current idea for the project’s future is to possibly refactor it using Electron. I will take note of your feedback, and I look forward to Vocab Manager being able to meet everyone again with more complete functionality someday :D

If you have any great ideas, you are also welcome to submit a pull request to the source code!
